name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jhnc-oss/images/python:3.10
    name: "Build"
    steps:
      - uses: actions/checkout@main
      - name: Setup
        run: |
          pip install -r requirements.txt
          dnf install -y findutils
      - name: oelint-adv
        run: |
          find . -type d \( -iname packagegroups \) -prune -false -o \
            \( -name "*.bb" -o -name "*.bbappend" \) \
            -exec oelint-adv {} +

